import "@/styles/globals.css";

import { Mulish } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";

import { Toaster } from "react-hot-toast";
import RecoilContextProvider from "@/providers/recoil-context-provider";

const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "PGB EVENT",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${mulish.variable}`}>
        <TRPCReactProvider headers={headers()}>
          <RecoilContextProvider>{children}</RecoilContextProvider>
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
